apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec: 
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources: 
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
