apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    pvc: meu-primeiro-pvc
  name: meu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: giropops
  selector:
    matchLabels:
      storage: nfs
